name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # allows SonarCloud to decorate PRs with analysis results
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven # enable maven cache shared by all github actions builds

      # to be able to use "sonar:sonar" instead of "org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"
      # inside this build but also when the test project analysis is launched with sonar:sonar
      - name: Configure Maven for Sonar
        run: |
          mkdir -p ~/.m2
          echo "<settings><pluginGroups><pluginGroup>org.sonarsource.scanner.maven</pluginGroup></pluginGroups></settings>" > ~/.m2/settings.xml

      - name: Cache SonarQube packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Verify
        run: ./mvnw -e -B verify

      - name: SonarQube Scan
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -z "$SONAR_TOKEN" ]; then
            echo "⚠️ SONAR_TOKEN is not set (Dependabot PR or external fork). Skipping SonarQube scan."
          else
            ./mvnw -e -B sonar:sonar -Dsonar.projectKey=green-code-initiative_creedengo-python -Dsonar.organization=green-code-initiative
          fi
